In [3]:
import numpy as np 

banking_data = np.array([
    [1001,  45000.75, 720,  45,  3],   # Customer 1
    [1002, 128000.00, 810, 120,  8],   # Customer 2
    [1003,  32000.50, 580,  22,  1],   # Customer 3
    [1004, 890000.25, 885, 210, 12],   # Customer 4
    [1005,  75000.00, 695,  78,  5],   # Customer 5
    [1006,  18000.90, 540,  15,  2],   # Customer 6
    [1007, 650000.40, 845, 180, 10],   # Customer 7
    [1008,  95000.60, 760,  95,  6],   # Customer 8
    [1009, 420000.00, 790, 150,  9],   # Customer 9
    [1010,  28000.30, 610,  38,  4]    # Customer 10
])

# Column names (for reference)
columns = np.array([
    "Customer_ID", #0
    "Account_Balance", #1
    "Credit_Score", #2
    "Transaction_Count", #3
    "Years_Active" #4
])

In [13]:
print(" Questions ")

print("\n Question 1: Array Creation and Manipulation ")

print("\n **Q1.1:** Create a 4x4 identity matrix using `np.eye()`")
print()
print(np.eye(4))


print("\n**Q1.2:** Create an array of 8 zeros using `np.zeros()`")
print()
print(np.zeros(8))


print("\n**Q1.3:** Create an array of 6 ones using `np.ones()`")
print()
print(np.ones(6))

print("\n**Q1.4:** Create an array with values from 0 to 15 using `np.arange()`")
print()
print(np.arange(16))

print("\n**Q1.5:** Create an array with 8 evenly spaced values from 0 to 100 using `np.linspace()`")
print()
print(np.linspace(0, 100, 8))

 Questions 

 Question 1: Array Creation and Manipulation 

 **Q1.1:** Create a 4x4 identity matrix using `np.eye()`

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

**Q1.2:** Create an array of 8 zeros using `np.zeros()`

[0. 0. 0. 0. 0. 0. 0. 0.]

**Q1.3:** Create an array of 6 ones using `np.ones()`

[1. 1. 1. 1. 1. 1.]

**Q1.4:** Create an array with values from 0 to 15 using `np.arange()`

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

**Q1.5:** Create an array with 8 evenly spaced values from 0 to 100 using `np.linspace()`

[  0.          14.28571429  28.57142857  42.85714286  57.14285714
  71.42857143  85.71428571 100.        ]


In [15]:
print(" Question 2: Array Attributes and Information ")

print("**Q2.1:** What is the shape of the `banking_data` array?")
print()
print(banking_data.shape)

print("\n**Q2.2:** What is the data type of the `banking_data` array?")
print()
print(banking_data.dtype)

print("\n *Q2.3:** What is the size (total number of elements) of the `banking_data` array?")
print(f"\n{banking_data.size}")

print("\n**Q2.4:** What is the number of dimensions of the `banking_data` array?")
print(f"\n{banking_data.ndim} ")

print("\n **Q2.5:** What is the memory size of the `banking_data` array in bytes?")
print(f"\n {banking_data.nbytes}")

 Question 2: Array Attributes and Information 
**Q2.1:** What is the shape of the `banking_data` array?

(10, 5)

**Q2.2:** What is the data type of the `banking_data` array?

float64

 *Q2.3:** What is the size (total number of elements) of the `banking_data` array?

50

**Q2.4:** What is the number of dimensions of the `banking_data` array?

2 

 **Q2.5:** What is the memory size of the `banking_data` array in bytes?

 400


In [16]:
print("\n Question 3: Indexing and Slicing")

print("\n **Q3.1:** Extract the first row of `banking_data`")
print(f"\n {banking_data[0,:]} ")

print("\n **Q3.2:** Extract the last row of `banking_data`")
print(f"\n {banking_data[-1, :]}")

print("\n **Q3.3:** Extract the Account_Balance column (column index 1)")
print(f"\n {banking_data[:, 1]} ")

print("\n **Q3.4:** Extract the first 4 rows and first 3 columns")
print(f"\n {banking_data[: 4, : 3]}")

print("\n **Q3.5:** Extract rows 3 to 7 (inclusive)")
print(f"\n {banking_data[2:7]}")


 Question 3: Indexing and Slicing

 **Q3.1:** Extract the first row of `banking_data`

 [1.001000e+03 4.500075e+04 7.200000e+02 4.500000e+01 3.000000e+00] 

 **Q3.2:** Extract the last row of `banking_data`

 [1.01000e+03 2.80003e+04 6.10000e+02 3.80000e+01 4.00000e+00]

 **Q3.3:** Extract the Account_Balance column (column index 1)

 [ 45000.75 128000.    32000.5  890000.25  75000.    18000.9  650000.4
  95000.6  420000.    28000.3 ] 

 **Q3.4:** Extract the first 4 rows and first 3 columns

 [[1.0010000e+03 4.5000750e+04 7.2000000e+02]
 [1.0020000e+03 1.2800000e+05 8.1000000e+02]
 [1.0030000e+03 3.2000500e+04 5.8000000e+02]
 [1.0040000e+03 8.9000025e+05 8.8500000e+02]]

 **Q3.5:** Extract rows 3 to 7 (inclusive)

 [[1.0030000e+03 3.2000500e+04 5.8000000e+02 2.2000000e+01 1.0000000e+00]
 [1.0040000e+03 8.9000025e+05 8.8500000e+02 2.1000000e+02 1.2000000e+01]
 [1.0050000e+03 7.5000000e+04 6.9500000e+02 7.8000000e+01 5.0000000e+00]
 [1.0060000e+03 1.8000900e+04 5.4000000e+02 1.5000000e

In [22]:

print("\n Question 4: Mathematical Operations")

print("\n **Q4.1:** Calculate the sum of all account balances")
print(f"\n {np.sum(banking_data[:,1]):.0f}")

print("\n **Q4.2:** Calculate the mean account balance")
print(f"\n {np.mean(banking_data[:,1]):.0f}")

print("\n **Q4.3:** Calculate the standard deviation of account balances")
print(f"\n {np.std(banking_data[:, 1]):.0f}")

print("\n **Q4.4:** Calculate the variance of account balances")
print(f"\n {np.var(banking_data[:, 1])}")

print("\n **Q4.5:** Calculate the median account balance ")
print(f"\n {np.median(banking_data[:, 1]):.0f}")


 Question 4: Mathematical Operations

 **Q4.1:** Calculate the sum of all account balances

 2381004

 **Q4.2:** Calculate the mean account balance

 238100

 **Q4.3:** Calculate the standard deviation of account balances

 293134

 **Q4.4:** Calculate the variance of account balances

 85927436576.0926

 **Q4.5:** Calculate the median account balance 

 85000


In [23]:
print("\n  Question 5: Statistical Functions ")

print("\n **Q5.1:** Find the minimum and maximum account balances")
print(f"\n minimum : {np.min(banking_data[:, 1])}, maximum : {np.max(banking_data[:, 1])}")

print("\n **Q5.2:** Find the minimum and maximum credit scores")
print(f"\n minimum : {np.min(banking_data[:, 2])}, maximum : {np.max(banking_data[:, 2])}")
     

print("\n **Q5.3:** Calculate the percentile values for account balances (25th, 50th, 75th)")
print(f"\n {np.percentile(banking_data[:, 2], [25, 50, 75])}")

print("\n **Q5.4:** Calculate the correlation between account balance and credit score")
print(f"\n {np.corrcoef(banking_data[:, 1], banking_data[:, 2])[0, 1]}")

print("\n **Q5.5:** Calculate the covariance between account balance and credit score")
print(f"\n {np.cov(banking_data[:, 1], banking_data[:, 2])}")


  Question 5: Statistical Functions 

 **Q5.1:** Find the minimum and maximum account balances

 minimum : 18000.9, maximum : 890000.25

 **Q5.2:** Find the minimum and maximum credit scores

 minimum : 540.0, maximum : 885.0

 **Q5.3:** Calculate the percentile values for account balances (25th, 50th, 75th)

 [631.25 740.   805.  ]

 **Q5.4:** Calculate the correlation between account balance and credit score

 0.7775637610022208

 **Q5.5:** Calculate the covariance between account balance and credit score

 [[9.54749295e+10 2.79790375e+07]
 [2.79790375e+07 1.35613889e+04]]


In [29]:
print("\n  Question 6: Array Reshaping and Manipulation")

print("\n **Q6.1:** Reshape the `banking_data` to 5 rows × 10 columns")
banking_data_copy = banking_data.copy()
print(f"\n {banking_data_copy.reshape(5, 10)}")

print("\n **Q6.2:** Flatten the `banking_data` to a 1D array")
print(f"\n {banking_data_copy.flatten()}")

print("\n **Q6.3:** Transpose the `banking_data`")
print(f"\n {banking_data.T}")

print("\n **Q6.4:** Split the `banking_data` into 2 equal parts vertically")
print(f"\n {np.vsplit(banking_data, 2)}")

print("\n **Q6.5:** Split the `banking_data` into 2 equal parts horizontally")
## print(f"\n {np.hsplit(banking_data, 2)}")


  Question 6: Array Reshaping and Manipulation

 **Q6.1:** Reshape the `banking_data` to 5 rows × 10 columns

 [[1.0010000e+03 4.5000750e+04 7.2000000e+02 4.5000000e+01 3.0000000e+00
  1.0020000e+03 1.2800000e+05 8.1000000e+02 1.2000000e+02 8.0000000e+00]
 [1.0030000e+03 3.2000500e+04 5.8000000e+02 2.2000000e+01 1.0000000e+00
  1.0040000e+03 8.9000025e+05 8.8500000e+02 2.1000000e+02 1.2000000e+01]
 [1.0050000e+03 7.5000000e+04 6.9500000e+02 7.8000000e+01 5.0000000e+00
  1.0060000e+03 1.8000900e+04 5.4000000e+02 1.5000000e+01 2.0000000e+00]
 [1.0070000e+03 6.5000040e+05 8.4500000e+02 1.8000000e+02 1.0000000e+01
  1.0080000e+03 9.5000600e+04 7.6000000e+02 9.5000000e+01 6.0000000e+00]
 [1.0090000e+03 4.2000000e+05 7.9000000e+02 1.5000000e+02 9.0000000e+00
  1.0100000e+03 2.8000300e+04 6.1000000e+02 3.8000000e+01 4.0000000e+00]]

 **Q6.2:** Flatten the `banking_data` to a 1D array

 [1.0010000e+03 4.5000750e+04 7.2000000e+02 4.5000000e+01 3.0000000e+00
 1.0020000e+03 1.2800000e+05 8.10000

In [ ]:
print("\n  Question 7: Logical Operations and Filtering ")

print("\n **Q7.1:** Find customers with account balance greater than $100,000")
print(f"\n {banking_data[banking_data[:, 1] > 100000]} ")

print("\n **Q7.2:** Find customers with credit score greater than 800")
print(f"\n {banking_data[banking_data[:, 2] > 800]}")

print("\n **Q7.3:** Find customers with transaction count greater than 50 AND credit score less than 750")
print(f"\n {banking_data[(banking_data[:, 3] > 50) & (banking_data[:, 2] < 750)]}")

print("\n **Q7.4:** Count how many customers have account balance between $10,000 and $100,000")
print(f"\n {np.sum(banking_data[(banking_data[:, 1]> 10000) & (banking_data[:, 1] < 100000)])}")

print("\n **Q7.5:** Find the index of the customer with the highest credit score")
print(f"\n {np.argmax(banking_data[:, 2])}")


  Question 7: Logical Operations and Filtering 

 **Q7.1:** Find customers with account balance greater than $100,000

 [[1.0020000e+03 1.2800000e+05 8.1000000e+02 1.2000000e+02 8.0000000e+00]
 [1.0040000e+03 8.9000025e+05 8.8500000e+02 2.1000000e+02 1.2000000e+01]
 [1.0070000e+03 6.5000040e+05 8.4500000e+02 1.8000000e+02 1.0000000e+01]
 [1.0090000e+03 4.2000000e+05 7.9000000e+02 1.5000000e+02 9.0000000e+00]] 

 **Q7.2:** Find customers with credit score greater than 800

 [[1.0020000e+03 1.2800000e+05 8.1000000e+02 1.2000000e+02 8.0000000e+00]
 [1.0040000e+03 8.9000025e+05 8.8500000e+02 2.1000000e+02 1.2000000e+01]
 [1.0070000e+03 6.5000040e+05 8.4500000e+02 1.8000000e+02 1.0000000e+01]]

 **Q7.3:** Find customers with transaction count greater than 50 AND credit score less than 750

 [[1.005e+03 7.500e+04 6.950e+02 7.800e+01 5.000e+00]]

 **Q7.4:** Count how many customers have account balance between $10,000 and $100,000

 303255.05

 **Q7.5:** Find the index of the customer with t

In [4]:
print("\n  Question 8: Sorting and Searching")

print("\n **Q8.1:** Sort the `banking_data` by account balance (ascending)")
print(f"\n {banking_data[banking_data[:, 1].argsort()]} ")

print("\n **Q8.2:** Sort the `banking_data` by credit score (descending)")
print(f"\n {(banking_data[np.argsort(-banking_data[:, 2])])}")

print("\n **Q8.3:** Find the indices that would sort the array by years active")
print(f"\n {banking_data[banking_data[:, 4].argsort()]}")

print("\n **Q8.4:** Find the customer with the second highest account balance")
print(f"\n {banking_data[np.argsort(banking_data[:, 1])[::-1][1]]} ")

print("\n **Q8.5:** Find the customer with the lowest transaction count")
print(f"\n {banking_data[np.argsort(banking_data[:, 3])[0]]}")

### Question 9: Mathematical Functions

print("\n **Q9.1:** Calculate the absolute values of all elements")
print(f"\n {np.abs(banking_data)}")

print("\n **Q9.2:** Calculate the square root of all account balances")
print(f"\n {np.sqrt(banking_data[:, 1])}")

print("\n **Q9.3:** Calculate the square of all credit scores")
print(f"\n {np.square(banking_data[:, 2])}")

print("\n **Q9.4:** Calculate the exponential of all transaction counts")
print(f"\n {np.exp(banking_data[:, 3])}")

print("\n **Q9.5:** Calculate the natural logarithm of all account balances")
print(f"\n {np.log(banking_data[:, 1])}")


  Question 8: Sorting and Searching

 **Q8.1:** Sort the `banking_data` by account balance (ascending)

 [[1.0060000e+03 1.8000900e+04 5.4000000e+02 1.5000000e+01 2.0000000e+00]
 [1.0100000e+03 2.8000300e+04 6.1000000e+02 3.8000000e+01 4.0000000e+00]
 [1.0030000e+03 3.2000500e+04 5.8000000e+02 2.2000000e+01 1.0000000e+00]
 [1.0010000e+03 4.5000750e+04 7.2000000e+02 4.5000000e+01 3.0000000e+00]
 [1.0050000e+03 7.5000000e+04 6.9500000e+02 7.8000000e+01 5.0000000e+00]
 [1.0080000e+03 9.5000600e+04 7.6000000e+02 9.5000000e+01 6.0000000e+00]
 [1.0020000e+03 1.2800000e+05 8.1000000e+02 1.2000000e+02 8.0000000e+00]
 [1.0090000e+03 4.2000000e+05 7.9000000e+02 1.5000000e+02 9.0000000e+00]
 [1.0070000e+03 6.5000040e+05 8.4500000e+02 1.8000000e+02 1.0000000e+01]
 [1.0040000e+03 8.9000025e+05 8.8500000e+02 2.1000000e+02 1.2000000e+01]] 

 **Q8.2:** Sort the `banking_data` by credit score (descending)

 [[1.0040000e+03 8.9000025e+05 8.8500000e+02 2.1000000e+02 1.2000000e+01]
 [1.0070000e+03 6.5000

In [ ]:

print("\n Question 10: Advanced Operations")

print("\n **Q10.1:** Calculate the cumulative sum of account balances")
print(f"\n {np.cumsum(banking_data[:,1])} ")

print("\n **Q10.2:** Calculate the cumulative product of transaction counts")
print(f"\n {np.cumprod(banking_data[:,3])}")

print("\n **Q10.3:** Calculate the difference between consecutive account balances")
print(f"\n {np.diff(banking_data[:, 1])}")

print("\n **Q10.4:** Calculate the gradient of account balances")
print(f"\n {np.gradient(banking_data[:, 1])}")

print("\n **Q10.5:** Calculate the histogram of account balances with 5 bins") 
print(f"\n {np.histogram(banking_data[:, 1], bins = 5)}")

print("\n Question 11: Random Numbers and Simulation")

print("\n **Q11.1:** Generate 6 random integers between 1 and 1000") 
print(f"\n {np.random.randint(1, 1001, 6)}")

print("\n **Q11.2:** Generate 6 random floats between 0 and 1") 
print(f"\n {np.random.rand(6)}")

print("\n **Q11.3:** Generate 6 random numbers from normal distribution (mean=700, std=100)") 
print(f"\n {np.random.normal(700, 100, 6)}")

print("\n **Q11.4:** Shuffle the `banking_data` rows randomly") 
print(f"\n {np.random.shuffle(banking_data)}")

print("\n **Q11.5:** Set random seed to 123 and generate 4 random numbers") 
np.random.seed(123)
print(f"\n {np.random.rand(4)}")

print("\n Question 12: Linear Algebra Operations")

print("\n **Q12.1:** Calculate the dot product of account balance and credit score columns") 
print(f"\n {np.dot(banking_data[:, 1], banking_data[:, 2])}")

print("\n **Q12.2:** Calculate the cross product of first two rows") 
print(f"\n {np.cross(banking_data[0, :3], banking_data[1, :3])}")

print("\n **Q12.3:** Calculate the norm (magnitude) of the account balance column")
print(f"\n {np.linalg.norm(banking_data[:, 1])}")

print(" \n **Q12.4:** Create a 3x3 matrix and calculate its determinant") 
A = np.array([[4, 7, 8],
            [4, 8, 9],
            [1, 2, 3]])
print(A)
print(f"\n {np.linalg.det(A)}")

print("\n **Q12.5:** Calculate the inverse of the 3x3 matrix") 
print(f"\n {np.linalg.inv(A)}")

print("\n Question 13: String Operations")

print("\n **Q13.1:** Convert all customer IDs to strings") 
customer_ids = banking_data[:, 0].astype(str)
print(f"\n {customer_ids}")

print("\n **Q13.2:** Check if any customer ID contains '100'")
print(f"\n {np.any(np.char.find(customer_ids, '100') > 0)}")

print(" \n **Q13.3:** Convert all customer IDs to uppercase (if they were strings)") 
print(f"\n {np.char.upper(customer_ids)}")

print("\n **Q13.4:** Count the length of each customer ID string") 
print(f"\n {np.char.str_len(customer_ids)}")

print("\n **Q13.5:** Replace '100' with 'CUST' in customer IDs") 
print(f"\n {np.char.replace(customer_ids, '100', 'CUST')} ")



 Question 10: Advanced Operations

 **Q10.1:** Calculate the cumulative sum of account balances

 [ 420000.   1070000.4  1098000.7  1193001.3  1321001.3  1396001.3
 1441002.05 2331002.3  2363002.8  2381003.7 ] 

 **Q10.2:** Calculate the cumulative product of transaction counts

 [1.50000000e+02 2.70000000e+04 1.02600000e+06 9.74700000e+07
 1.16964000e+10 9.12319200e+11 4.10543640e+13 8.62141644e+15
 1.89671162e+17 2.84506743e+18]

 **Q10.3:** Calculate the difference between consecutive account balances

 [ 230000.4  -622000.1    67000.3    32999.4   -53000.    -29999.25
  844999.5  -857999.75  -13999.6 ]

 **Q10.4:** Calculate the gradient of account balances

 [ 230000.4   -195999.85  -277499.9     49999.85   -10000.3    -41499.625
  407500.125   -6500.125 -435999.675  -13999.6  ]

 **Q10.5:** Calculate the histogram of account balances with 5 bins

 (array([7, 0, 1, 1, 1]), array([ 18000.9 , 192400.77, 366800.64, 541200.51, 715600.38, 890000.25]))

 Question 11: Random Numbers and

In [33]:

print("\n Question 14: Date and Time Operations")

columns = np.array([
    "Customer_ID", #0
    "Account_Balance", #1
    "Credit_Score", #2
    "Transaction_Count", #3
    "Years_Active" #4
])

print("\n **Q14.1:** Convert years active to months")

years_active = banking_data[:, 4]

print(f"\n {years_active * 12}")

print("\n **Q14.2:** Calculate the average years active") 

print(f"\n {np.mean(years_active)}")

print("\n **Q14.3:** Find customers who have been active for more than 5 years") 

print(f"\n {banking_data[(years_active > 5)]}")

print("\n **Q14.4:** Calculate the total time all customers have been active (in years)") 

print(f"\n {np.sum(years_active)}")

print("\n **Q14.5:** Find the customer with the shortest time active") 

print(f"\n {banking_data[np.argmin(years_active)]}")

print("\n  Question 15: Advanced Array Operations")

print("\n **Q15.1:** Apply a function to calculate 5% interest on all account balances") 

print(f"\n {banking_data[:,1]*1.05}")

print("\n **Q15.2:** Use `np.where` to categorize customers by balance ranges" ) 

print(f"\n {np.where((banking_data[:, 1] > 100000), " high_balance ", "low_balance")}")

print("\n **Q15.3:** Use `np.select` to categorize customers by credit score ranges" ) 

conditions = [
    banking_data[:, 2] < 600, 
    banking_data[:, 2] < 700,
    banking_data[:, 2] >= 700
]

choices = ["poor", "fair", "excellent"]

print(f"\n {np.select(conditions, choices, default = "unknown")}")

print("\n **Q15.4:** Use `np.piecewise` to apply different interest rates based on balance" ) 

balance = banking_data[:, 1]

def low_rate(x): return x * 0.5 
def medium_rate(x): return x * 1
def high_rate(x): return x * 1.5 

conditions = [balance < 50000, balance < 200000, balance >= 200000]
interest = np.piecewise(balance, conditions, [low_rate, medium_rate, high_rate])

print(f"\n {interest}")

print("\n **Q15.5:** Use `np.apply_along_axis` to calculate the sum of each row") 

print(f"\n {banking_data.sum(axis = 1)}")

print("\n Question 16: Array Concatenation and Stacking")

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([[7], [8], [9]])


print("\n **Q16.1:** Concatenate two arrays horizontally using `np.hstack()`")

print(f"\n {np.hstack((a, b))}")

print("\n **Q16.2:** Concatenate two arrays vertically using `np.vstack()`") 

print(f"\n {np.vstack((a, b))} ")

print("\n **Q16.3:** Concatenate arrays along a specific axis using `np.concatenate()`") 

print(f"\n {np.concatenate((a,b), axis = 0)}")

print("\n **Q16.4:** Stack arrays depth-wise using `np.dstack()`") 

print(f"\n {np.dstack((a, b))}")

print("\n **Q16.5:** Create a column stack using `np.column_stack()`" ) 

print(f"\n {np.column_stack((a, b))}")

print("\n  Question 17: Array Splitting Operations ")

arr = np.arange(12)

print("\n **Q17.1:** Split an array into 3 equal parts using `np.split()`" ) 

print(f"\n {np.split(arr, 3)}")

print("\n **Q17.2:** Split an array at specific indices using `np.split()`") 

print(f"\n {np.split(arr, [3, 7])}")

print("\n **Q17.3:** Split an array horizontally using `np.hsplit()`")

print(f"\n {np.hsplit(arr, 2)}")

print("\n **Q17.4:** Split an array vertically using `np.vsplit()`") 

arr = arr.reshape(4, 3)
print(f"\n {np.vsplit(arr, 2)}")

print("\n **Q17.5:** Split an array into equal chunks using `np.array_split()`") 

print(f"\n {np.array_split(arr, 5)}")

print("\n  Question 18: Array Repetition and Tiling ")

print("\n **Q18.1:** Repeat each element of an array 3 times using `np.repeat()`") 

print(f"\n {np.repeat(arr, 3)}")

print("\n **Q18.2:** Repeat an entire array 2 times using `np.tile()`") 

print(f"\n {np.tile(arr, 2)}")

print("\n **Q18.3:** Repeat a 2D array using `np.tile()`") 

array_2d = np.array(([[1, 2], [3, 4]]))

print(f"\n {np.tile(array_2d, 2)}")

print("\n **Q18.4:** Create a pattern using `np.tile()`") 

print(f"\n {np.tile(np.array([[2, 3], [4, 5]]), (4, 4))}")

print("\n **Q18.5:** Repeat elements with different counts using `np.repeat()`") 

print(f"\n {np.repeat(a, [1, 2, 3])}")

print("\n Question 19: Array Comparison and Logical Operations ") 


print("\n **Q19.1:** Compare two arrays for equality using `np.array_equal()`") 

x = np.array([1, 2, 3, 4])
y = np.array([1, 2, 3, 5])
print(f"\n {np.array_equal(x, y)}")

print("\n **Q19.2:** Check if arrays are close using `np.allclose()`") 

print(f"\n {np.allclose(x, y, atol = 2)}")

print("\n **Q19.3:** Apply logical AND operation between arrays") 

print(f"\n logical_and : {np.logical_and(a,b)} ")
print(f"\n {(x > 1) & (y > 1)}")

print("\n **Q19.4:** Apply logical OR operation between arrays") 

print(f"\n logical_or : {np.logical_or(a, b)}")
print(f"\n {(x <= 1) | (y > 3)}")

print("\n **Q19.5:** Apply logical NOT operation to an array") 

print(f" {np.logical_not(a)}")
print(f"\n {~(x > 2)}")

print("\n Question 20: Array Set Operations")

print("\n **Q20.1:** Find unique elements in an array using `np.unique()`") 

d = np.array([1, 2, 3, 4, 3, 4, 5])

print(f"\n {np.unique(d)}")

print("\n **Q20.2:** Find the intersection of two arrays using `np.intersect1d()`") 

print(f"\n {np.intersect1d(x, y)}")

print("\n **Q20.3:** Find the union of two arrays using `np.union1d()`") 

print(f"\n {np.union1d(x, y)}")

print("\n **Q20.4:** Find elements in first array but not in second using `np.setdiff1d()`") 

print(f"\n {np.setdiff1d(x, y)}")

print("\n **Q20.5:** Find the symmetric difference between two arrays using `np.setxor1d()`") 

print(f"\n {np.setxor1d(x, y)}")





 Question 14: Date and Time Operations

 **Q14.1:** Convert years active to months

 [144.  48.  24.  36.  72. 120. 108.  60.  12.  96.]

 **Q14.2:** Calculate the average years active

 6.0

 **Q14.3:** Find customers who have been active for more than 5 years

 [[1.0040000e+03 8.9000025e+05 8.8500000e+02 2.1000000e+02 1.2000000e+01]
 [1.0080000e+03 9.5000600e+04 7.6000000e+02 9.5000000e+01 6.0000000e+00]
 [1.0070000e+03 6.5000040e+05 8.4500000e+02 1.8000000e+02 1.0000000e+01]
 [1.0090000e+03 4.2000000e+05 7.9000000e+02 1.5000000e+02 9.0000000e+00]
 [1.0020000e+03 1.2800000e+05 8.1000000e+02 1.2000000e+02 8.0000000e+00]]

 **Q14.4:** Calculate the total time all customers have been active (in years)

 60.0

 **Q14.5:** Find the customer with the shortest time active

 [1.00300e+03 3.20005e+04 5.80000e+02 2.20000e+01 1.00000e+00]

  Question 15: Advanced Array Operations

 **Q15.1:** Apply a function to calculate 5% interest on all account balances

 [934500.2625  29400.315   18900.94